### ISSUE TITLE
Elifecycle error

### ISSUE THREAD

**Issue by Thesabanrab** [HashLips/hashlips_nft_minting_dapp#5]
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.14.15
3 info using node@v14.17.6
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle hashlips_nft_minting_dapp@1.0.0~prestart: hashlips_nft_minting_dapp@1.0.0
6 info lifecycle hashlips_nft_minting_dapp@1.0.0~start: hashlips_nft_minting_dapp@1.0.0
7 verbose lifecycle hashlips_nft_minting_dapp@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle hashlips_nft_minting_dapp@1.0.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;E:\New folder\NFT script\hashlips_nft_minting_dapp-1.0.0\node_modules\.bin;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64_win\compiler;C:\Program Files (x86)\Razer Chroma SDK\bin;C:\Program Files\Razer Chroma SDK\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Users\John\AppData\Local\Microsoft\WindowsApps;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files\Common Files\Autodesk Shared\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Users\John\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0;C:\Program Files\nodejs\;C:\ProgramData\chocolatey\bin;C:\users\john\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages;C:\Users\John\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\John\AppData\Roaming\npm
9 verbose lifecycle hashlips_nft_minting_dapp@1.0.0~start: CWD: E:\New folder\NFT script\hashlips_nft_minting_dapp-1.0.0
10 silly lifecycle hashlips_nft_minting_dapp@1.0.0~start: Args: [ '/d /s /c', 'react-scripts start' ]
11 silly lifecycle hashlips_nft_minting_dapp@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle hashlips_nft_minting_dapp@1.0.0~start: Failed to exec start script
13 verbose stack Error: hashlips_nft_minting_dapp@1.0.0 start: `react-scripts start`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:400:28)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:400:28)
13 verbose stack     at maybeClose (internal/child_process.js:1055:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid hashlips_nft_minting_dapp@1.0.0
15 verbose cwd E:\New folder\NFT script\hashlips_nft_minting_dapp-1.0.0
16 verbose Windows_NT 10.0.19042
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "start"
18 verbose node v14.17.6
19 verbose npm  v6.14.15
20 error code ELIFECYCLE
21 error errno 1
22 error hashlips_nft_minting_dapp@1.0.0 start: `react-scripts start`
22 error Exit status 1
23 error Failed at the hashlips_nft_minting_dapp@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
this i the error I'm getting any idea how to fix. I tried the suggestions, but none of them seem to want to work

**Comment by adobortnik** [comment]
Have u managed to fix this?
